site_name: Rules Engine
nav:
  - Getting Started: index.md
  - Install: install.md
  - When/Then: when_then.md
  - Run/RunAll: run_vs_run_all.md
  - Operators:
    - not_: not.md
    - all_: all.md
    - any_: any.md
  - Full Example: full_example.md

theme:
  name: "material"
  palette:
    primary: "teal"
  logo: assets/logo.png
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
