site_name: Rules Engine
nav:
  - Getting Started: index.md
  - Install: install.md
  - When/Then: when_then.md
  - Operators:
    - not_: not.md
    - all_: all.md
    - any_: any.md
  - Basic Example: basic_example.md

theme:
  name: "material"
  palette:
    primary: "teal"
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
